languageCode = "ja-jp"
title = "on-my-owl"
theme = "hugo-swift-theme"
paginate = 6
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
baseURL = "https://blog.yiyenene.club/"

[params]
    description = "個人の感想です"
    twitter = "yiyenene"

[taxonomies]
    tag = "tags"