backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title",name: "title",widget: "string"}
      - {label: "Date",name: "date",widget: "datetime"}
      - {label: "Author",name: "author",widget: "hidden",default: "yiyenene"}
      - {label: "Image",name: "image",widget: "image"}
      - {label: "Tags",name: "tags",widget: "list", default: ["emo", "code", "umaumauma"]}
      - {label: "Draft",name: "draft",widget: "boolean", default: "true"}
